backend:
  name: git-gateway
  repo: freie-schule-bergmeilen/website
  branch: master # Branch to update (optional; defaults to master)

media_folder: "/src/pages/img"
public_folder: "../img"

collections:

  - name: "news" # Used in routes, e.g., /admin/collections/blog
    label: "Aktuelles" # Used in the UI
    folder: "src/pages/news" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {name: kind, widget: hidden, default: "news"}
      - {label: "Template", name: "templateKey", widget: "hidden", default: "news-item" }
      - {label: "Layout", name: "layout", widget: "hidden", default: "news"}
      - {label: "Pfad", name: "path", widget: "string"}
      - {label: "Titel", name: "title", widget: "string"}
      #- {label: "Image", name: "image", widget: "image", required: false}
      - {label: "Datum", name: "date", widget: "datetime"}
      - {label: "Pin", name: "pin", widget: "boolean", required: false}
      - {label: "Text", name: "body", widget: "markdown"}

  - name: pages
    label: Seiten
    folder: "src/pages/pages"
    create: true
    slug: "{{slug}}"
    fields:
      - {name: kind, widget: hidden, default: "page"}
      - {label: "Template", name: "templateKey", widget: "hidden", default: page }
      - {label: "Pfad", name: "path", widget: "string"}
      - {label: "Titel", name: "title", widget: "string"}
      - label: Bereich
        name: section
        widget: select
        options: ["Angebot", "Philosophie", "Über uns"]
        default: "Angebot"
      - {label: "Text", name: "body", widget: "markdown"}
      - {name: order, label: Position, widget: number, default: 0}


  - name: team
    label: Team
    folder: "src/pages/team"
    create: true
    slug: "{{slug}}"
    fields:
      - {name: dataKind, widget: hidden, default: "team-member"}
      - {name: title, label: Name}
      - {name: position, label: "Funktion an der Schule"}
      - {name: experience, label: "Ausbildung/Berufserfahrung", required: false}
      - {name: image, label: Foto, widget: image, required: false, class: "team"}
      - name: children
        label: Kinder
        widget: list
        required: false
        fields:
          - {label: Name, name: name, widget: string}
          - {label: Year, name: year, widget: string}
      - {name: order, label: Position, widget: number, default: 0}
      - {name: body, widget: hidden, default: ""}

#          - {name: name, label: Name}
#          - {name: position, label: "Funktion and der Schule"}
#          - {name: experience, label: "Ausbildung/Berufserfahrung", widget: text, required: false}
#          - {name: image, label: Foto, widget: image, required: false, class: "team-member" }
#          - name: children
#            label: Kinder
#            widget: list
#            required: false
#            fields:
#              - {label: Name, name: name, widget: string}
#              - {label: Year, name: year, widget: string}


  - name: "settings"
    label: "Sonstiges"
    delete: false
    editor:
      preview: false
    files:
      - name: "metadata"
        label: "Globale Einstellungen"
        file: "data/site-metadata.yml"
        description: "Einstellungen"
        fields:
          - {label: "Name der Webseite", name: title, widget: "string"}
          - {label: "Google Analytics UA-Code", name: trackingId, widget: "string"}
          - {label: "Anzahl News auf Homepage", name: numNewsItems, widget: number}
          - label: "Meta"
            name: meta
            widget: object
            fields:
              - label: Beschreibung
                name: description
                widget: text
                required: false
              - label: Stichwörter
                name: keywords
                widget: text
                required: false


      - name: "goals"
        label: Ziele
        file: "data/goals.yml"
        description: "Ziele"
        fields:
          - {label: "Überschrift", name: title, widget: "string"}
          - name: goals
            label: Ziele
            widget: list
            fields:
              - {label: "Überschrift", name: title, widget: string}
              - {label: Beschreibung, name: description, widget: text, required: false}

      - name: "hero"
        label: "Homepage Hero"
        file: "data/hero.yml"
        description: "Ziele"
        fields:
          - {label: "Überschrift", name: title, widget: string}
          - {label: "Text", name: text, widget: text}

